### ISSUE TITLE
after installation the centralized-relay command cant be found

### ISSUE THREAD

**Issue by FidelVe** [icon-project/centralized-relay#107]
after cloning the repo and running `make install` I try to execute the `centralized-relay --version` command but I get the following error:

```
$ centralized-relay --version
-bash: centralized-relay: command not found                
```

**Comment by debendraoli** [comment]
Wiki is fast forward and in sync with current development.
We had previously binary name `crly` shortcut to `centralized-relay`, but we eventually ended with longer name `centralized-relay`.

You can call `crly` as you might be `main` branch which is yet merged with development branch.

Alternately, 
If just want to run `centralized-relay` binary, you can avoid cloning and building yourself rather easily download from release page assets, <https://github.com/icon-project/centralized-relay/releases/tag/v1.0.0>

**Comment by FidelVe** [comment]
Both commands are giving me errors

```
$ centralized-relay --version
-bash: centralized-relay: command not found
$ crly --version
-bash: crly: command not found
```

**Comment by debendraoli** [comment]
Then, it probably somethings to do with your system `$PATH`.

    Add the go binary path to the system environment variable.

    ```shell
    export PATH=$PATH:$GOPATH/bin
    ```

    Make it permanent by adding the above command to the `.bashrc` file.

    ```zsh
    echo "export PATH=$PATH:$GOPATH/bin" >> ~/.bashrc ## for bash
    echo "export PATH=$PATH:$GOPATH/bin" >> ~/.zshrc ## for zsh
    ```

**Comment by FidelVe** [comment]
thanks for the reply.

I doubt is an issue with go since it is already properly installed and is being used by other scripts and programs with no issue
```
$ which go
/usr/local/go/bin/go
$ go version
go version go1.21.5 linux/amd64
```

if after executing the installation steps the execution doesnt work we should either add the extra steps required to make it work in the instructions or refactor the `make install` command to make sure the installation works properly

**Comment by FidelVe** [comment]
re-running `make install` only outputs the following

```
$ make install
installing centralized rly binary...
```

**Comment by debendraoli** [comment]
> thanks for the reply.
> 
> I doubt is an issue with `go` since it is already properly installed and is being used by other scripts and programs with no issue
> 
> ```
> $ which go
> /usr/local/go/bin/go
> $ go version
> go version go1.21.5 linux/amd64
> ```
> 
> if after executing the installation steps the execution doesnt work we should either add the extra steps required to make it work in the instructions or refactor the `make install` command to make sure the installation works properly

Even go is installed properly you have to export `$GOPATH/bin` directory in order to binaries to be available.

**Comment by FidelVe** [comment]
please add the following steps to the tutorial to make it easier for users to fix this error:

```
After installation add the GOPATH directory to your PATH in order for the binaries created by Go to be accessible to the system.

To obtain the GOPATH run the following
go env GOPATH

Add the go binary path to the system environment variable.

export PATH=$PATH:$GOPATH/bin

Make it permanent by adding the above command to the .bashrc file.

bash:

echo "export PATH=$PATH:$GOPATH/bin" >> ~/.bashrc

zsh:

echo "export PATH=$PATH:$GOPATH/bin" >> ~/.zshrc
```

**Comment by FidelVe** [comment]
im continuing with the installation/configuration steps and im getting the following errors

```
$ crly config init
Error: mkdir /home/admin-1/.centralized-relay: file exists
$ rm -rf ~/.centralized-relay/
$ crly config init
Error: mkdir /home/admin-1/.centralized-relay: file exists
```

The command is failing because the `~/.centralized-relay/` folder already exists, im deleting the folder and re running the command but it says again that the folder already exists

**Comment by pragyanshrestha-ibriz** [comment]
https://github.com/icon-project/centralized-relay/pull/134
