### ISSUE TITLE
recommendation for updating the centralized relay documentation

### ISSUE THREAD

**Issue by FidelVe** [icon-project/centralized-relay#133]
The following is a list of recommendation to improve the documentation of the centralized relay documentation after going to the process of executing all the required steps.

Currently the documentation to fully setup a working centralized relay is fragmented, we have the following docs:
* [xcall-multi/docs/centralized-connection](https://github.com/icon-project/xcall-multi/blob/main/docs/centralized-connection.md). This file appears to be the entry point it describes that we need to first go thru the process of deploying the contracts for the centralized connection and then installing the relayer and setting up.
* [xcall-multi/docs/centralized-connection-setup](https://github.com/icon-project/xcall-multi/blob/main/docs/centralized-connection-setup.md) this file describes the process of compiling and deploying the contracts for the centralized connection
* [centralized-relay/wiki](https://github.com/icon-project/centralized-relay/wiki) this wiki describes the installation process of the centralized relay

Improvements that can be done here:

* add to the [centralized-relay/wiki/installation](https://github.com/icon-project/centralized-relay/wiki/Installation) document the link to the [xcall-multi/docs/centralized-connection-setup](https://github.com/icon-project/xcall-multi/blob/main/docs/centralized-connection-setup.md) as a prerequisite
* currently one part of the steps (deploying the contracts) is in the xcall-multi repo and the other part of the steps (installing and configuring the relayer) is in the centralized-relay wiki, this makes it hard for newcomers to know what to do and what process to follow, we should have everything in one place

Also as a recommendation, describe the steps required in the case the centralized relayer is not going to be running on an ec2 instance on AWS, during a call a couple of weeks back with prod-support It was described that some set of steps can be bypass if the centralized relayer is not running on AWS

**Comment by debendraoli** [comment]
Addressed.
