### ISSUE TITLE
Utilize go workspace rather the single `go.mod` to separate dependencies between main module and e2e module

### ISSUE THREAD

**Issue by debendraoli** [icon-project/centralized-relay#184]
We have lots of dependencies that includes the deps from e2e and main project together which can be challenging for project hygiene and security aspect endpoint.

Go workspace feature is built to address such scenarios.

**Comment by bcsainju** [comment]
Since it would be better to integrate this functionality before merging the changes in e2e and reworking later, this has been incorporated in the ticket related to the e2e integration ticket.
