### ISSUE TITLE
[Discover] Administration tools for relayer.

### ISSUE THREAD

**Issue by debendraoli** [icon-project/centralized-relay#192]
This proposal is for relayer administration tool that includes and not limited to the following features:

- API endpoints that can be exposed externally
- Permissioned endpoints that verifies the each request for execution.
- External service apart from relayer.

**Comment by debendraoli** [comment]
I have thought of writing the service externally. This way we can avoid doing everything on relayer and do complex logic.

- Service exposes endpoints with auth
- Serice accepts request and calls crly cmds, etc

**Comment by debendraoli** [comment]
Auth flow:

- Config option to allow array of wallets that can send message.
- Verify signed message.
- Execute the request.

**Comment by debendraoli** [comment]
Allowed requests:

- Restart relayer using height.
- Manual relay.
- Download logs

**Comment by AntonAndell** [comment]
Wallets might be unnecessary? Aren't there finished software packages with more traditional authentications?
Perhaps even a small UI built into it. Should exist readily.
This would allow us to fix issues even from a phone or any device.

**Comment by debendraoli** [comment]
architecture. 
https://github.com/icon-project/relayer-admin-dashboard/blob/main/docs/architecture.pdf
