### ISSUE TITLE
Centralized Relay - Optimization

### ISSUE THREAD

**Issue by pragyanshrestha-ibriz** [icon-project/centralized-relay#264]
Review currently centralized relay architecture to improve stability, reliability and security for the relay.

**Comment by bcsainju** [comment]
Regarding the stability and reliability, most of the unstable parts i.e. syncing between websockets and regular RPC calls have been handled to certain extent. The areas where we can make some modifications are as:
- Currently the locks/limitation on number of concurrent transaction is limited in the inner level i.e. while executing transaction but not on the upper level where they are scheduled. Limitation on scheduling can be implemented to hold less txns in memory and pass through db when processing slow.
- Add some mechanism to slow processing of chains in case of constant error with RPC or network congestion issues until the scenario becomes normal with periodic retries.
- For certain errors, re-trying may not make send for txns. For such txn with specified errors, don't retry at all.
- Need to work on observability (metrics/logs) to track and react on underlying issues if any.
- As a general convention, we should stick to single source either websocket or general RPC or grpc whichever is available, for less complexity in the application while getting events from the chain.

For security part, they have been covered via earlier ticket at https://github.com/icon-project/ICON-Projects-Planning/discussions/426

<img width="1927" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFNSQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5b5e0a421da7b6b84c19e9dd410e647030ed679/Centralized_Relayer.png" alt="Centralized_Relayer.png" />

 Relayer basic Flow

**Comment by bcsainju** [comment]
Regarding the stability and reliability, most of the unstable parts i.e. syncing between websockets and regular RPC calls have been handled to certain extent. The areas where we can make some modifications are as:
- Currently the locks/limitation on number of concurrent transaction is limited in the inner level i.e. while executing transaction but not on the upper level where they are scheduled. Limitation on scheduling can be implemented to hold less txns in memory and pass through db when processing slow.
- Add some mechanism to slow processing of chains in case of constant error with RPC or network congestion issues until the scenario becomes normal with periodic retries.
- For certain errors, re-trying may not make send for txns. For such txn with specified errors, don't retry at all.
- Need to work on observability (metrics/logs) to track and react on underlying issues if any.
- As a general convention, we should stick to single source either websocket or general RPC or grpc whichever is available, for less complexity in the application while getting events from the chain.

For security part, they have been covered via earlier ticket at https://github.com/icon-project/ICON-Projects-Planning/discussions/426

<img width="1927" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFNSQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5b5e0a421da7b6b84c19e9dd410e647030ed679/Centralized_Relayer.png" alt="Centralized_Relayer.png" />

 Relayer basic Flow

**Comment by debendraoli** [comment]
> Implement signal handling for cleaner exit,resource cleanup and reload if required.

This is already implemented from the start.

> For certain errors, re-trying may not make sense for txns. For such txn with specified errors, don't retry at all.

Very tricky to get this done, sometime it leads to false postive. retrying make sense and does not hurts retrying. 

> Need to work on observability (metrics/logs) to track and react on underlying issues if any.

I guess this is should be on priority as we're going for monitoring solutions soon, other than that it's battle tested and works very well in current situation.

**Comment by bcsainju** [comment]
In the case of signal handling, the resources are not cleaned up properly as we get the socket issue during crashes.

For the case of aborting retry, it should be only for very well known cases and retrying would block the processing so it will have an impact when the processing queues are large.

**Comment by debendraoli** [comment]
> In the case of signal handling, the resources are not cleaned up properly as we get the socket issue during crashes.

It's very well handled on production use case.
Also this is tricky situation, we have cli in place where it connects to it.
It may lead to race condition.

**Comment by bcsainju** [comment]
How can the same code work differently in different scenarios ? Also the server resource in not properly cleaned up after crash I am not sure how it would lead to race condition after the program itself crashes . Did if I miss something ?

**Comment by debendraoli** [comment]
> How can the same code work differently in different scenarios ? Also the server resource in not properly cleaned up after crash I am not sure how it would lead to race condition after the program itself crashes . Did if I miss something ?

Yeah, service is responsible for cleaning the lingering resources.

There is service descriptor on our installation wiki guide.

**Comment by bcsainju** [comment]
In that case i think we should remove the below line from wiki and make it mandatory for everyone to run the relayer as service defined in the wiki otherwise the resource cleanup will be an issue. .

_This is only required if you want to run the relay as a service._

**Comment by debendraoli** [comment]
I have already stated that on point 6 already.

> This step will guide you through the configurating the relay to run as a service on the system using systemd init system.
> This is only required if you want to run the relay as a service.

**Comment by bcsainju** [comment]
Either we should mark the lack of resource cleanup as a feature and add in documents appropriately for other deployments or we should fix the resource cleanup in the relayer itself and not relaying on deployer scripts.

**Comment by bcsainju** [comment]
As per internal discussion, the relayer is mostly stable and the above fixes while helpful might not solve the actual issue. So, it is paused for now and will resume once the monitoring has been implemented with in-depth logs analysis.
