### ISSUE TITLE
Update document for running e2e test

### ISSUE THREAD

**Issue by DeepakBomjan** [icon-project/centralized-relay#339]
### What needs to be done

- The current help guide for running E2E documentation is not easy to follow.
- There are many inaccuracies and mistakes in the information provided.

### Why it needs to be done

Following the guide/steps provided in the help guide, anyone should be able to run the test successfully.

### List of Items to fix/update
1. The current centralized relay binary does not provide adequate logging for errors; it only prints a memory trace and panics. For example, running the command `centralized-relay chains list` will result in a panic if `centralized-relay init` has not been executed.

2. The `E2E_CONFIG_PATH` environment variable is not functioning correctly. Even when a custom path is set, the E2E framework still loads the config file from the default location, `test/sample-config.yaml`.

3. There is a spelling error in the icon keystore file name. The file is named `godWallet.json`, but the E2E framework expects it to be `godwallet.json`.

**Comment by bcsainju** [comment]
fixed in PR #360
